// Complete episodes data from The WIP Meetup YouTube channel
// Generated from YouTube analytics export

export interface EpisodeData {
  videoId: string;
  title: string;
  publishDate: string;
}

export const EPISODES_DATA: EpisodeData[] = [
  { videoId: "H_HqMJ4pRBs", title: "The WIP Meetup 3/5/2026", publishDate: "Mar 5, 2026" },
  { videoId: "98lMPTGZpcc", title: "The WIP Meetup 2/26/2026 Raw Footage ft Dragonate body part removal charity drive & hyperfy v2 peek", publishDate: "Feb 27, 2026" },
  { videoId: "i0EQ50k8Aeg", title: "The WIP Meetup 01/11/2024 Metageist Race Commentary", publishDate: "Feb 12, 2024" },
  { videoId: "8jLOVvAbgLU", title: "The WIP Meetup 08/29/2024 Raw Footage ft Buildtree Alpha & Roustan BlockBuster Video Field Trip", publishDate: "Aug 29, 2024" },
  { videoId: "n74Nu9HIjHE", title: "The WIP Meetup 09/19/2024 Raw Footage ft Jin aka DankVR with the Openvoxels Deep Dive", publishDate: "Sep 20, 2024" },
  { videoId: "qYL2vJks3Zg", title: "The WIP Meetup 06/11/2020 Ft AlottaMoney 1st Sponsorship + Mintbase, NFTfi, MetaCartel, PoolTogether", publishDate: "Feb 27, 2024" },
  { videoId: "EDkxw8lVpuo", title: "The WIP Meetup 04/06/2020 Speaker Portion ft. Ezincrypto, Jihoz, Andrew Steinwold & Johan", publishDate: "Jan 26, 2024" },
  { videoId: "lyeA_lJdQns", title: "The WIP Meetup 02/20/2025 ft 105Collective & MetaRick tour of Hyperfy V2 Mashup by Paradoxx", publishDate: "Mar 3, 2025" },
  { videoId: "_-nQ06AYRqA", title: "The WIP Meetup 02/20/2025 Raw Footage ft 105 Collective & MetaRick tour of Hyperfy V2", publishDate: "Feb 21, 2025" },
  { videoId: "bPcNuSGiuPQ", title: "The WIP Meetup 02/06/2025 ft Bay Backner Kim Currier @decentraland_foundationToxsam Mash by Paradoxx", publishDate: "Feb 7, 2025" },
  { videoId: "tuk_IC8f_jY", title: "The WIP Meetup 07/09/2020 Coldie speaker portion on the incredible Kitty Bungalow fundraiser", publishDate: "Feb 2, 2024" },
  { videoId: "ZkYp54P23CI", title: "Sho ridicules DragoNate with man in underwear", publishDate: "Oct 4, 2025" },
  { videoId: "2hEJrbxNFiw", title: "Getting ready for the Dreamverse with Metapurse's Twobadour & Brooke", publishDate: "Mar 28, 2025" },
  { videoId: "8Il7I-m2MeA", title: "The WIP Meetup 07/18/2024 Raw Footage ft FlyFrogs Decentralized 3D Printing Toys & Composable Frogs", publishDate: "Jul 18, 2024" },
  { videoId: "ijEnUKTKPb4", title: "The WIP Meetup 08/01/2024 THEADH3ADS ft FrankyNeedles Mashup by Paradoxx", publishDate: "Aug 7, 2024" },
  { videoId: "g_6MJbkznHQ", title: "The WIP Meetup 06/27/2024 Decentraland Game Expo Mashup by Paradoxx", publishDate: "Jul 18, 2024" },
  { videoId: "cbfb6cQ13p8", title: "The WIP Meetup 01/09/2025 Raw Footage ft. Colborn, Reneil, Jin, Rizzlefest Skunkwurkz w/ Trislit", publishDate: "Jan 10, 2025" },
  { videoId: "4Ngg1e03E-g", title: "The WIP Meetup 03/13/2025 Raw Footage ft Lucho Poletti w/ Bankrunners & Burcin IO w/ BasedForest", publishDate: "Mar 14, 2025" },
  { videoId: "FaUneAAh-Lw", title: "The WIP Meetup 09/05/2024 Raw Footage ft Paradoxx Lumens, Meme.com NFA, Rizzle talking RizzleFest", publishDate: "Sep 6, 2024" },
  { videoId: "Sfh9nHoS-_s", title: "The WIP Meetup 1/16/2026 Raw Footage ft GeorgeBoya Hiddenforces @fractilians Animal Spawn Bonanza", publishDate: "Jan 16, 2026" },
  { videoId: "Xe_bOLFuupw", title: "The WIP Meetup 06/26/2025 Raw Footage ft Jaen Art Exhibit & Untitledxyz & Nedos w/ Comput3.ai", publishDate: "Jun 27, 2025" },
  { videoId: "t6zjNtvSFys", title: "The WIP Meetup 02/01/2024 Raw Footage ft. Flyfrogs breeding & Nifty Island gaming", publishDate: "Feb 7, 2024" },
  { videoId: "8tLq55UVnek", title: "The WIP Meetup 02/17/2022 Raw Footage ft StudioTBD, Jeremy Cowart & Hot DougsNFT", publishDate: "Feb 18, 2022" },
  { videoId: "eYeaMJXk_eU", title: "AlottaMoney 50th Birthday Celebration of Life Party ft. Music by Eclectic Method Mashup by Paradoxx", publishDate: "Jun 14, 2024" },
  { videoId: "051ZyBBMoEM", title: "The WIP Meetup 07/24/2025 Raw Footage ft Flyfrog3D + Flyfrogger game by Paradoxx & Nineoverzero", publishDate: "Jul 25, 2025" },
  { videoId: "RL6W35v2LUE", title: "The WIP Meetup 10/29/2020 Ḳ𝖎𝖙𝖙𝖞 𝕭𝖆𝖘𝖙 speaker portion linking physical to digital art nfts", publishDate: "Feb 9, 2024" },
  { videoId: "j1uhC602saE", title: "The WIP Meetup 10/17/2024 Raw Footage ft Kim Currier Decentraland Alpha & VjDelaria Day of the Dead", publishDate: "Oct 17, 2024" },
  { videoId: "AxU6b7_inck", title: "The WIP Meetup 2020 Early Decentraland Exploration ft. Voxel Architects & Franky Needles", publishDate: "Feb 20, 2024" },
  { videoId: "DcYDHBp3phY", title: "The WIP Meetup 03/27/2025 Raw Footage ft OONA & Paradoxx WIP Parcel rebuild in hyperfy", publishDate: "Mar 28, 2025" },
  { videoId: "WlF4VYaf7Yw", title: "The WIP Meetup 09/19/2024 ft OpenVoxels & Jin / DankVr Mashup by CheddarQueso3D", publishDate: "Sep 25, 2024" },
  { videoId: "5aQT2AAbLhk", title: "The WIP Meetup 06/13/2024 Raw Footage ft FelixFelixFelix, Benoit & Cypherdudes Deep Dive", publishDate: "Jun 14, 2024" },
  { videoId: "BwZwJlM8Lvg", title: "The WIP Meetup 07/30/2020 Ezincrypto in NonFunGerbils Hamster Wheel w/ Impromtu Song by RoganX4", publishDate: "Mar 15, 2024" },
  { videoId: "L-okxuih1FQ", title: "[Special Interview] Diving Deep Into Opensea with CEO Devin Finzer", publishDate: "Mar 28, 2025" },
  { videoId: "jbpX6i3s1QQ", title: "The WIP Meetup 06/18/2020 Ft. Trippyogi, Vandal, Vesa + Field Trip w/ Hiddenforces, Tom Erik Smith", publishDate: "Feb 23, 2024" },
  { videoId: "uIsBT9byahs", title: "The Flywheel Strategy", publishDate: "Sep 30, 2025" },
  { videoId: "yOUy0qkc0XQ", title: "Metalympics 2020 Teaser by Paradoxx", publishDate: "May 17, 2024" },
  { videoId: "-SqHKnOqnZg", title: "The WIP Meetup 08/06/2020 Rendar Art Cryptovoxels Mashup by Paradoxx", publishDate: "Apr 9, 2024" },
  { videoId: "GqpoWQF_SWg", title: "The WIP Meetup 2020 Ghost Agent Token Smelter in the Rendar Gallery Mashup by Paradoxx", publishDate: "May 3, 2024" },
  { videoId: "KVV2QiGllEo", title: "The WIP Meetup 08/28/2025 Raw Footage ft Sho & Rizzle $WIP surprise unveiling", publishDate: "Aug 29, 2025" },
  { videoId: "W3s0D-ABu3U", title: "The WIP Meetup 2/22/2024 Raw Footage Ft. HubzzHQ & Russfranky", publishDate: "Feb 23, 2024" },
  { videoId: "odVsoispuwg", title: "The WIP Meetup 05/15/2025 Raw Footage ft Roustan Tour & Deep Dive into Hyperfy 2.0", publishDate: "May 16, 2025" },
  { videoId: "sjUhfA6R8pg", title: "The WIP Meetup 03/31/2022 The Paradoxx Theme Song Live Unveiling", publishDate: "Mar 8, 2024" },
  { videoId: "77yz9q2fLh8", title: "The WIP Meetup 03/28/2024 Decentraland Art Week w/ Bay Backner Mashup by Paradoxx", publishDate: "Apr 10, 2024" },
  { videoId: "3Kv4JyLdQwU", title: "The WIP Meetup 12/21/2023 Raw Footage Merry WIPmas massive #anontree nft giveaway + Reneil🎄", publishDate: "Dec 22, 2023" },
  { videoId: "GpRRg_qCu5o", title: "The WIP Meetup 02/13/2025 Raw Footage ft Artacle.io, Meme NFA w/ Johan + WIPSON ai w/ HiddenForces", publishDate: "Feb 14, 2025" },
  { videoId: "l19ZsKrpJHQ", title: "The WIP Meetup 2020 PranskyLand Tour in Cryptovoxels Mashup by Paradoxx", publishDate: "Apr 12, 2024" },
  { videoId: "rwYLDnJSnPA", title: "The WIP Meetup 02/29/2024 Raw Footage Ft. Metageist Game Building & Elated Pixels Voxel Tour", publishDate: "Feb 29, 2024" },
  { videoId: "AP3ogxMp3wY", title: "The WIP Meetup 12/19/2024 Raw Footage ft. Merry WIPMAS Plane crash adventure w/ Paradoxx & Metageist", publishDate: "Dec 20, 2024" },
  { videoId: "Hn6Tjor-Db0", title: "The WIP Meetup 02/21/2024 HubzzHQ Play Test w/ RussFranky Mashup by Paradoxx", publishDate: "Feb 28, 2024" },
  { videoId: "krFJYRdexfQ", title: "The WIP Meetup 09/04/2025 Raw Footage ft Rocketman & Cobuild", publishDate: "Sep 5, 2025" },
  { videoId: "loCV93uOETA", title: "The WIP Meetup 03/20/2025 ft BayBackner, MAKEANFT, @decentraland_foundation LosCat Mash by Paradoxx", publishDate: "Mar 27, 2025" },
  { videoId: "p74132sdDDM", title: "The WIP Meetup 03/20/2025 Raw Footage ft Bay Backner, MAKEANFT, @decentraland_foundation, Los Cat", publishDate: "Mar 21, 2025" },
  { videoId: "wXvhk5RnzcI", title: "[Spotlight] An animated conversation with JisuArtist", publishDate: "Mar 28, 2025" },
  { videoId: "0WnLwQ8_Nbs", title: "The WIP Meetup 08/26/2021 ft Johan w/ Meme.com, SkyGolpe, Alex from Koii Network Mashup by Paradoxx", publishDate: "Apr 17, 2025" },
  { videoId: "PXGvdekJB_E", title: "The WIP Meetup 04/08/2021 ft Coldie, NFT Plazas, Spaced Painter, MetaJax, Mashup by Paradoxx", publishDate: "Aug 23, 2024" },
  { videoId: "SfYrkuSZyeo", title: "Drifters in the Metaverse with Josie Bellini", publishDate: "May 14, 2025" },
  { videoId: "_-O9lCmNnzo", title: "The WIP Meetup 05/04/2023 Raw Footage ft The State of the Metaverse Panel", publishDate: "May 5, 2023" },
  { videoId: "vCvetj59TaY", title: "The WIP Meetup 08/14/2025 Raw Footage ft TheBeatMiner Drag Racing Event in Substrata", publishDate: "Aug 15, 2025" },
  { videoId: "1X8sSt6HGZY", title: "The WIP Meetup 06/01/2023 Raw Footage ft. Async Art & Utopia Labs", publishDate: "Jun 2, 2023" },
  { videoId: "5pq8laex-eI", title: "The WIP Meetup 03/28/2024 Raw Footage Ft MESHfair tour in Decentraland w/ Bay Backner", publishDate: "Mar 29, 2024" },
  { videoId: "6bjaGenUum8", title: "Metalympics Closing Video Mashup \"Where You There?\" by Paradoxx", publishDate: "Jun 25, 2024" },
  { videoId: "9KxdP2iqqzs", title: "The Metalympics 11/05/2020 Week 1 Voxel Architects Obstacle Course Mashup by Paradoxx", publishDate: "May 24, 2024" },
  { videoId: "Qhqh92RLiME", title: "The WIP Meetup 11/20/2025 Raw Footage ft Wipsgiving 2025 Pt 1", publishDate: "Nov 21, 2025" },
  { videoId: "VIzO6rWB6lE", title: "The WIP Meetup 10/22/20 Connie Digital speaker portion talking music nfts & social tokens", publishDate: "Feb 5, 2024" },
  { videoId: "WqyhqdWy9-U", title: "The WIP Meetup 02/21/2024 AL Crego & Snail0x Mashup by Paradoxx", publishDate: "Feb 21, 2024" },
  { videoId: "XSnSjhcAhqQ", title: "The WIP Meetup 04/21/2022 Raw Footage ft DAO Records, Varien & Punkscape", publishDate: "Apr 22, 2022" },
  { videoId: "mojgUcqb5Hw", title: "The WIP Meetup 05/16/2024 dverso.io Mashup by Paradoxx", publishDate: "Jun 7, 2024" },
  { videoId: "EaEMGatFZBo", title: "The WIP Meetup 06/03/2021 Metaverse Wearable Shopping Spree Mashup by Paradoxx", publishDate: "Jan 15, 2025" },
  { videoId: "HuoAEEohUoo", title: "The WIP Meetup 12/05/2025 Raw Footage ft MrRichi & Money Laundering 2", publishDate: "Dec 5, 2025" },
  { videoId: "IVMSINiEQTY", title: "The WIP Meetup 04/11/2024 Raw Footage ft. Fabiano Sandbox Game & Competition", publishDate: "Apr 12, 2024" },
  { videoId: "Knor_-9jlII", title: "The WIP Meetup 08/20/2020 Group Skydiving off Fabiano Clod in Cryptovoxels", publishDate: "Mar 27, 2024" },
  { videoId: "j1SU-QMv2gA", title: "The WIP Meetup 10/31/2024 Raw Footage Ft. Hyperfy Halloween w/ the WIP Crew", publishDate: "Nov 1, 2024" },
  { videoId: "k4dbYmA08Jo", title: "The WIP Meetup 04/01/2021 Gary Cartlidge, Sam Brukhman, Stina Jones, Bittrees Egg Mashup by Paradoxx", publishDate: "Jul 22, 2024" },
  { videoId: "kS4fU7zW5Eo", title: "The WIP Meetup 04/25/2024 CyberBrokers Takeover Mashup by Paradoxx", publishDate: "May 1, 2024" },
  { videoId: "lPwgSt3ukfY", title: "[Special Interview] SuperRare CEO John Crain on building a crypto art marketplace", publishDate: "Mar 28, 2025" },
  { videoId: "xK98kbyKdm0", title: "The WIP Meetup 1/22/2026 Raw Footage ft Matt's Awkward Retirement Party", publishDate: "Jan 23, 2026" },
  { videoId: "-fQWgh5TVLk", title: "The WIP Meetup 09/12/2024 Raw Footage ft Ol1y Art Deep Dive,Fabiano Rat Party, Rizzlefest Drivers Ed", publishDate: "Sep 13, 2024" },
  { videoId: "H8Y9pQZ-1sk", title: "The WIP Meetup 03/27/2025 ft Paradoxx WIP Parcel, OONA Art Exhibit & Egg Race Mashup by Paradoxx", publishDate: "Apr 2, 2025" },
  { videoId: "HjBXgYHEB1I", title: "The WIP Meetup 03/06/2025 Raw Footage ft HPrivakos, ElatedPixel Voxels Tour + AlottaMoney Tribute🙏", publishDate: "Mar 7, 2025" },
  { videoId: "MWHQ_U3Wjr8", title: "The WIP Meetup 02/06/2025 Raw Footage ft Bay Backner, Kim Currier @decentraland_foundation & Toxsam", publishDate: "Feb 7, 2025" },
  { videoId: "WYlQYEaxpz8", title: "The WIP Meetup 05/20/2021 Crime Ridden Rendar Art Gallery Mashup by Paradoxx", publishDate: "Nov 22, 2024" },
  { videoId: "ZgUNO5dOuPE", title: "The WIP Meetup 06/27/2024 Raw Footage ft DCLGX Panel w/ Niftytime + DCL Wearable Hunt w/ Bay Backner", publishDate: "Jun 27, 2024" },
  { videoId: "f31_yDKN5TI", title: "The WIP Meetup 04/03/2025 Raw Footage ft AtBarbieLove, HiddenForces & Paradoxx Metaverse Skate Ramp", publishDate: "Apr 4, 2025" },
  { videoId: "fFGxTNCJop8", title: "The WIP Meetup 7/25/2024 Timelapse FlyFrogs to JOY Parcel by Rizzle", publishDate: "Aug 5, 2024" },
  { videoId: "g8JJJOrr0AA", title: "The WIP Meetup 04/15/2021 ft Spherical Art, Jacob Martin, Kinchasa, Ezincrypto", publishDate: "Aug 30, 2024" },
  { videoId: "mBHuMLWTDHU", title: "The WIP Meetup 08/22/2024 Raw Footage ft The Phygital Food Project & Metageist Anonyboxes", publishDate: "Aug 23, 2024" },
  { videoId: "yul_XUxRTNM", title: "The WIP Meetup 08/29/2024 ft Buildtree, Roustan, & Blockbuster Field Trip Mashup by Paradoxx", publishDate: "Sep 5, 2024" },
  { videoId: "5tZeX03dilE", title: "The WIP Meetup 06/06/2024 HubzzHQ Mashup by Paradoxx", publishDate: "Jun 12, 2024" },
  { videoId: "E-h72NwQivQ", title: "The WIP Meetup 11/21/2024 Raw Footage ft. WIPGIVING PARADE w/ StinaJones, Dankvr, Ezincrypto, Rizzle", publishDate: "Nov 22, 2024" },
  { videoId: "F2LXIkshJAA", title: "Metaverse Monetization Musings & Purple Apps", publishDate: "Apr 22, 2025" },
  { videoId: "GiW4ZkntnaU", title: "The WIP Meetup 07/31/2025 Raw Footage ft Kane Mayfield Reading Ridiculous Product Descriptions", publishDate: "Aug 1, 2025" },
  { videoId: "J9_pz7F7Qmg", title: "The WIP Meetup 11/19/2020 Speaker Portion ft Roham from Dapperlabs & NBA Top Shot", publishDate: "Mar 18, 2024" },
  { videoId: "T3gw4bAiw2w", title: "The WIP Meetup 06/25/2020 Superrare, Gitcoin, Sparrow, Whaleshark at Scarlet Factory by AlottaMoney", publishDate: "Mar 1, 2024" },
  { videoId: "WHl7672Q6zo", title: "The WIP Meetup 1/8/2026 Raw Footage ft Oona Under Surveillance & The Dear David Project", publishDate: "Jan 10, 2026" },
  { videoId: "Xc991goMzec", title: "The WIP Meetup 07/16/2020 Early Cryptovoxels Wearable Montage by Paradoxx", publishDate: "Mar 5, 2024" },
  { videoId: "clhTmPoGK_o", title: "The WIP Meetup 06/20/2024 Raw Footage ft George Boya & Barbie S.A.", publishDate: "Jun 21, 2024" },
  { videoId: "hgmILcTKzx8", title: "The WIP Meetup 05/29/2025 Raw Footage ft Tipn alpha w/ Niftytime & Babacci mint w/ Rizzle", publishDate: "May 30, 2025" },
  { videoId: "llKyzLj8Vx4", title: "The WIP Meetup 2020 Cryptovoxels Bronx Zoo Mashup by Paradoxx", publishDate: "Apr 19, 2024" },
  { videoId: "qP428JKJ4Zw", title: "The WIP Meetup 01/26/2024 Raw Footage ft. Decentraland Wellness Week w/ Bay Backner & Fractilians", publishDate: "Jan 26, 2024" },
  { videoId: "uQIsVrqe_y4", title: "The Metalympics 11/12/2020 Week 2 Stacks Race Mashup by Paradoxx", publishDate: "Jun 7, 2024" },
  { videoId: "1hwIKxuh-5s", title: "The WIP Meetup 09/13/2020 Early Field Trip mashup from Coldie to NateAlex's spot in Cryptovoxels", publishDate: "Mar 22, 2024" },
  { videoId: "1nOODItFZjE", title: "The WIP Meetup 04/18/2024 Raw Footage Ft. Bay Backner Spatial Art Gallery Tour & Metageist Gaming", publishDate: "Apr 19, 2024" },
  { videoId: "8qhml6uqpEw", title: "The WIP Meetup 11/06/2025 Raw Footage ft Meme.com Launch & Paradoxx Alpha + New WIP Server Kickoff", publishDate: "Nov 7, 2025" },
  { videoId: "BoXgTrwKVDg", title: "The WIP Meetup 02/08/24 Aavegotchi Takeover Event Mashup by Paradoxx", publishDate: "Feb 14, 2024" },
  { videoId: "JdTLmDsQg9U", title: "The WIP Meetup 07/17/2025 Raw Footage ft Tipn deep dive & making it rain w/ Matt aka Niftytime", publishDate: "Jul 18, 2025" },
  { videoId: "SMR_Udn0TMQ", title: "The WIP Meetup 05/02/2024 VIPE Grifter Squaddie Takeover Mashup by Paradoxx", publishDate: "May 7, 2024" },
  { videoId: "U_nLdzyLYGw", title: "The WIP Meetup 05/02/2024 Raw Footage ft. Grifter Squaddies by Toxsam, Cynxx, & Vipe", publishDate: "May 3, 2024" },
  { videoId: "ecuZdbM2Vzg", title: "Making Metaverse Moves with Dirk Lueth, Co-founder of Upland", publishDate: "Mar 28, 2025" },
  { videoId: "l1fFf2B4M58", title: "The WIP Meetup 08/07/2025 Raw Footage ft ZCreativeMedia & the CoralVerse", publishDate: "Aug 8, 2025" },
  { videoId: "lZ8PLAuuUyo", title: "[Special Interview] Caty Tedman, Head of Marketing & Partnerships at Dapper Labs", publishDate: "Mar 28, 2025" },
  { videoId: "oSlQEwxTWu4", title: "The WIP Meetup 09/23/2021 Metalympic Stadium w/ DigitalX, Julie Pacino, LuchoPoletti Paradoxx Mash", publishDate: "Sep 17, 2025" },
  { videoId: "qT6xXFUrEzA", title: "Old crypto. Slow crypto. Long crypto", publishDate: "Mar 28, 2025" },
  { videoId: "uDBrYHUgTKk", title: "The WIP Meetup 10/30/2025 Raw Footage ft Ride Park 2 Grand Opening in Substrata w/ TheBeatMiner", publishDate: "Oct 31, 2025" },
  { videoId: "0orMajvsuFc", title: "The WIP Meetup 12/18/2025 Raw Footage ft WIPMAS 2025 Prize & Disaster Fest by Rizzle", publishDate: "Dec 19, 2025" },
  { videoId: "5OijqTDWELI", title: "The WIP Meetup 01/16/2025 Raw Footage ft Breaking Everything in Hyperfy w/ Fractilians", publishDate: "Jan 17, 2025" },
  { videoId: "8-LCrUvySiM", title: "The WIP Meetup 09/11/2025 Raw Footage ft Arthr Babyfest 2025 VRM drop", publishDate: "Sep 12, 2025" },
  { videoId: "FB_XbS2fCjE", title: "The WIP Meetup 10/29/2020 Speaker Portion ft. Micah Johnson", publishDate: "Feb 17, 2024" },
  { videoId: "Jj_QfbmM6zQ", title: "The WIP Meetup 03/07/2024 Stina Jones MarbleCards Event & Paradoxx Nifty Island Death by Paradoxx", publishDate: "Mar 12, 2024" },
  { videoId: "L245O7zW-_g", title: "The WIP Meetup 09/12/2024 ft Ol1y Art, Fabiano Speziari Rats,Metaverse Drivers Ed Mashup by Paradoxx", publishDate: "Sep 19, 2024" },
  { videoId: "Oxki0e1knNM", title: "The WIP Meetup 05/06/2021 ft Soundcamp, Leyline & Chainscribe Mashup by Paradoxx", publishDate: "Oct 14, 2024" },
  { videoId: "admp2ZxK7kc", title: "The WIP Meetup 04/03/2025 ft AtBarbieLove, HiddenForces, Metaverse Ramp Build & Mashup by Paradoxx", publishDate: "Apr 7, 2025" },
  { videoId: "fC-u3LrFxac", title: "The WIP Meetup 09/09/2021 ft Ethlings, VerticalCrypto, Fuego.eth, LuckyManekiNFT Mashup by Paradoxx", publishDate: "Apr 25, 2025" },
  { videoId: "hBfCzxzI0Lw", title: "The WIP Meetup 11/19/2020 DeFi Dad speaker portion talking defi, nfts & early days at zapper", publishDate: "Feb 19, 2024" },
  { videoId: "lPiv6MZRMjw", title: "The WIP Meetup 08/16/2024 Raw Footage ft Bryan Brinkman, Young & Sick + Charl3s from @niftyisland", publishDate: "Aug 16, 2024" },
  { videoId: "tKPN9prPj3M", title: "The WIP Meetup 03/21/2024 Raw Footage Ft. Charl3s from Nifty Island 1/2", publishDate: "Mar 22, 2024" },
  { videoId: "uUCtUnOB4ZE", title: "Purple App Praise Fest", publishDate: "Apr 2, 2025" },
  { videoId: "vVgjYRu-DQo", title: "Larping as an artist & F*cking marketing", publishDate: "Mar 28, 2025" },
  { videoId: "5WZOfAQKt5w", title: "The WIP Meetup 04/24/2025 Raw Footage ft BullyMeow & iamjudasjudas Music Drop, Race & Live Set", publishDate: "Apr 25, 2025" },
  { videoId: "DC7eh7wJEJo", title: "The WIP Meetup 06/19/2025 Raw Footage ft @decentraland_foundation game night w/ Bay Backner", publishDate: "Jun 20, 2025" },
  { videoId: "HcGrK-orekM", title: "The WIP Meetup 03/14/2024 Raw Footage ft FlexasaurusRex w/ VendingNFTS & Arthr", publishDate: "Mar 15, 2024" },
  { videoId: "K2BXSSmSPN4", title: "[Special Interview] A chat with Chris Dawe, CEO of Effect.AI", publishDate: "Mar 28, 2025" },
  { videoId: "L58-LQUCf1g", title: "The WIP Meetup 12/14/2023 Raw Footage DON'T CLICK ANYTHING naked metaverse streaking for safety", publishDate: "Dec 14, 2023" },
  { videoId: "LTAWDWheGkg", title: "The WIP Meetup 09/26/2024 Raw Footage ft Ludovica from Zeroone & Chauncey St. John from BetterGiving", publishDate: "Sep 26, 2024" },
  { videoId: "MjPhiUnzYVA", title: "The WIP Meetup 08/22/2024 ft The Phygital Food Project & Metageist Anonyboxes Mashup by Paradoxx", publishDate: "Aug 28, 2024" },
  { videoId: "Nvrpok1H4gE", title: "The WIP Meetup 2020 Crashing Cryptovoxels Mashup by Paradoxx", publishDate: "Apr 22, 2024" },
  { videoId: "Oc9i-eLEAlY", title: "The WIP Meetup 12/05/2025 Raw Footage ft RiverMouth District Opening in Substrata", publishDate: "Dec 12, 2025" },
  { videoId: "S10exnY4JX8", title: "The WIP Meetup 09/25/2025 Raw Footage ft @decentraland_foundation Art Week w/ Bay Backner", publishDate: "Sep 26, 2025" },
  { videoId: "TWarm0HvafU", title: "The WIP Meetup 04/18/2024 Spatial Tour w/ Bay Backner & Metageist Murderfest Mashup by Paradoxx", publishDate: "Apr 24, 2024" },
  { videoId: "WlEQBwd18nU", title: "The WIP Meetup 07/30/2020 NonFunGerbils Jump Course Mashup by Paradoxx", publishDate: "Apr 27, 2024" },
  { videoId: "dcoWMUxNZpI", title: "The WIP Meetup 12/19/2024 Merry WIPMAS Plane Crash w/ Paradoxx & Metageist", publishDate: "Jan 2, 2025" },
  { videoId: "eeW35ZeJc0s", title: "An on-chain discussion with Snowfro about Art Blocks", publishDate: "Mar 28, 2025" },
  { videoId: "gSylNsfbrPU", title: "The WIP Meetup 10/19/2023 Raw Footage Ft. Figurines of the Future Private Gallery Tour w/ Metageist", publishDate: "Oct 20, 2023" },
  { videoId: "le0SUn8fsjc", title: "The WIP Meetup 04/07/2022 Raw Footage ft Vector Meldrew, Mr. Y & Pixa Wizards", publishDate: "Apr 8, 2022" },
  { videoId: "3hv56xVFYHM", title: "The WIP Meetup 06/10/2021 ft Ethlings, AnonymousNobody & RussFranky Mashup by Paradoxx", publishDate: "Jan 31, 2025" },
  { videoId: "3t7rClPeJAI", title: "[Spotlight] Chatting CryptoCubes, Generative Art & Metaverse Exploring with Han", publishDate: "Mar 28, 2025" },
  { videoId: "Av4mUX-6rRg", title: "The WIP Meetup 05/19/2022 Raw Footage ft CryptoArcade, Ottis, Maria-Helena-Trad", publishDate: "May 20, 2022" },
  { videoId: "BfLmmIHU_7M", title: "The WIP Meetup 08/08/2024 Raw Footage ft HiddenForces, Rebase.Finance & Metageist", publishDate: "Aug 8, 2024" },
  { videoId: "CyIaI4-dPsU", title: "The WIP Meetup 04/29/2021 ft GiselX, AllyGrounds, Jonathan Wolfe & Snax RarePizza Mashup by Paradoxx", publishDate: "Sep 27, 2024" },
  { videoId: "EHAHX4C_ZnI", title: "The WIP Meetup 02/23/2023 Raw Footage ft Eclectic Method, NeonGlitch, FlyfrogsNFT, Seaofarrows", publishDate: "Feb 24, 2023" },
  { videoId: "EQhlOkCwZYM", title: "The WIP Meetup 10/16/2025 Raw Footage ft Bababbi V2 Alpha Drop + VoxCon Preview", publishDate: "Oct 17, 2025" },
  { videoId: "EXa1t1kCrsM", title: "The WIP Meetup 01/30/2025 Raw Footage ft [Redacted] beta tour🥷+ Don't Get Sidelined", publishDate: "Jan 31, 2025" },
  { videoId: "HmCLtF9HifE", title: "Diving down the PartyDAO rabbit hole with Steve K.", publishDate: "Mar 28, 2025" },
  { videoId: "JbW0_txZFFo", title: "The WIP Meetup 05/09/2024 Meme.com & WizardX Mashup by Paradoxx", publishDate: "May 15, 2024" },
  { videoId: "O6Ay-4dFb08", title: "The WIP Meetup 07/01/2021 ft HerStoryDAO, SuperWorld, Carlos Marcial & Ezincrypto Mashup by Paradoxx", publishDate: "Feb 5, 2025" },
  { videoId: "Pi6rOwElnRE", title: "The WIP Meetup 08/15/2024 ft ft Bryan Brinkman, Young & Sick @niftyisland Mashup by Paradoxx", publishDate: "Aug 22, 2024" },
  { videoId: "RGaE-Q1cUgQ", title: "The WIP Meetup 05/01/2025 Raw Footage ft Subs.fun + Fabiano & Rizzle w/ the Babacci Project", publishDate: "May 2, 2025" },
  { videoId: "SaZATdlLjew", title: "The WIP Meetup 10/12/2023 Raw Footage Ft. Fabiano Maze & Sandbox Game Preview + CodeTrip Race", publishDate: "Oct 13, 2023" },
  { videoId: "U6_2Yv6kjLM", title: "The WIP Meetup 07/25/2024 Raw Footage ft Jake from Base Colors & Live 3D Sculpting with JoyWorld", publishDate: "Jul 26, 2024" },
  { videoId: "W0e2WJbi4Yo", title: "The WIP Meetup 02/29/2024 Elated Pixels Street Tour & Metageist Gaming Mashup by Paradoxx", publishDate: "Mar 7, 2024" },
  { videoId: "YvViGIH5NJM", title: "The WIP Meetup 02/24/2022 Raw Footage ft Stellabelle, Bitlectro, Hunky Heroes & FlyfrogsNFT", publishDate: "Feb 25, 2022" },
  { videoId: "bcDx_9I9vJc", title: "The WIP Meetup 1/29/2026 Raw Footage ft Smoke the Artist", publishDate: "Jan 30, 2026" },
  { videoId: "d0CQaswtnkE", title: "Introducing NFT Protocol with Blockparty's Vlad & Joseph", publishDate: "Mar 28, 2025" },
  { videoId: "dc1cuikwxCE", title: "The WIP Meetup 05/22/2025 Raw Footage ft @decentraland_foundation Pre-Prom Prep w/ Bay Backner", publishDate: "May 23, 2025" },
  { videoId: "hdIMfZjgwow", title: "The WIP Meetup 02/08/2024 Raw Footage ft. Aavegotchi updates & live Gotchi gaming", publishDate: "Feb 9, 2024" },
  { videoId: "t8DVH7K8nzQ", title: "The WIP Meetup 04/27/2023 Raw Footage ft. YAT, FrankyNeedles & Juxton", publishDate: "Apr 28, 2023" },
  { videoId: "tIN3VfvV-P0", title: "The WIP Meetup 08/12/2021 ft SongCamp, Carguin, CryptoSpectr & DeployStarship Paradoxx Mashup", publishDate: "Mar 19, 2025" },
  { videoId: "tj4wQOsFNhU", title: "The WIP Meetup 06/17/2021 ft Toxsam, Leyline & RARAsocial Mashup by Paradoxx", publishDate: "Feb 3, 2025" },
  { videoId: "tpzk6lcpBj8", title: "The WIP Meetup 02/15/2024 Raw Footage Ft. AL Crego & 0xSnail Pirate Adventure🏴‍☠️", publishDate: "Feb 16, 2024" },
  { videoId: "zgJjx7vPXrE", title: "The WIP Meetup 07/03/2024 Raw Footage Ft. Stina Jones MarbleCards Event & Paradoxx WIP Island Battle", publishDate: "Mar 8, 2024" },
  { videoId: "3IrfP4PuiRc", title: "The WIP Meetup 2020 Breaking SteadyBreaks Parcel in Cryptovoxels Mashup by Paradoxx", publishDate: "Apr 29, 2024" },
  { videoId: "A2Rur2ona48", title: "The WIP Meetup 01/04/2024 Raw Footage Ft. Reniel at Amber Island", publishDate: "Jan 5, 2024" },
  { videoId: "CYvMlbQMtTs", title: "The WIP Meetup 11/21/2024 WIPGIVING PARADE w/ Stina, Dankvr, Ezincrypto, Rizzle, Mashup by Paradoxx", publishDate: "Dec 2, 2024" },
  { videoId: "FYxyjiy0r5U", title: "Rizzle chats with Found3r & ChangeDAO co-founders about using crypto to make real world change", publishDate: "Mar 28, 2025" },
  { videoId: "H18GwoDhcZE", title: "The WIP Meetup 09/02/2021 Mavenarte, Bored Becky, Squiggle DAO & Gluewave, Rizzle's Apt by Paradoxx", publishDate: "Apr 23, 2025" },
  { videoId: "HMqLEwDzyYg", title: "The WIP Meetup 07/25/2024 JOY Live 3D Drawing Mashup by Paradoxx", publishDate: "Aug 1, 2024" },
  { videoId: "RoDJaVgz0s8", title: "The WIP Meetup 08/19/2021 ft KnownOrigin Cryptovoxels Gallery, RaraSocial, KittyBast & Varian", publishDate: "Mar 24, 2025" },
  { videoId: "a_C4vr5m1fc", title: "The WIP Meetup 10/24/2025 Raw Footage ft TheBeatMiner not so mini-tour of Cryptovoxels", publishDate: "Oct 24, 2025" },
  { videoId: "axmk9KeHQjw", title: "The WIP Meetup 01/16/2025 ft Hyperfy Breakage Tour w/ Fractilians", publishDate: "Jan 23, 2025" },
  { videoId: "dP0aDsYE6Dg", title: "The WIP Meetup 06/16/2022 Raw Footage ft Louie C Rhymes, Ensemble & RareGotchi", publishDate: "Jun 17, 2022" },
  { videoId: "jRvNdQN-f7Q", title: "MEME, MARS & Lisbon", publishDate: "Jun 24, 2025" },
  { videoId: "jmkKzRylBAc", title: "The WIP Meetup 04/14/2022 Raw Footage ft Onchainchain, Rizzle, RareScrilla, Pepelangelo, NFTsnapback", publishDate: "Apr 14, 2022" },
  { videoId: "mSrCtW0I3-A", title: "Discussing Ducks, NFTs, and the Waves Blockchain with Sasha Ivanov", publishDate: "Mar 28, 2025" },
  { videoId: "mhfIXkJHfOQ", title: "The WIP Meetup 08/24/2023 Raw Footage Ft. Firefly App & Museum of CryptoArt", publishDate: "Aug 25, 2023" },
  { videoId: "rtvKtRET-Vg", title: "$WIP Q&A with Sho", publishDate: "Sep 17, 2025" },
  { videoId: "sVkZ9Ql5Sn4", title: "The WIP Meetup 06/13/2024 Cypherdudes Mashup by Paradoxx", publishDate: "Jun 20, 2024" },
  { videoId: "vDylIM0E0QM", title: "The WIP Meetup 04/10/2025 Mr Richi Cashgrabbers, @decentraland_foundation Fashion Mashup by Pardoxx", publishDate: "Apr 15, 2025" },
  { videoId: "ybdnclJHZzU", title: "The WIP Meetup 10/31/2024 Hyperfy Halloween Mashup by Paradoxx", publishDate: "Nov 7, 2024" },
  { videoId: "yoEjYKLN_U4", title: "The WIP Meetup 01/11/2024 Raw Footage ft Gabe Weiss, Cynxx from VIPE & Metageist Hyperfy jump course", publishDate: "Jan 12, 2024" },
  { videoId: "4H_rn-dIdiI", title: "Cent Spotlight - Waxing Philosophical on Hip Hop & Cent with DJ Lethal Skillz", publishDate: "Mar 28, 2025" },
  { videoId: "6k2rsdwOv8o", title: "The WIP Meetup 09/26/2024 ft Zeroone & BetterGiving Mashup by Paradoxx", publishDate: "Sep 30, 2024" },
  { videoId: "7tXSHR7yCvk", title: "The Metalympics Crowning of the Champions Mashup by Paradoxx🥇🥈🥉", publishDate: "Jun 25, 2024" },
  { videoId: "8-bIcCjKhhU", title: "The WIP Meetup 03/03/2022 Raw Footage ft RareCandy, DecentraFive & The Lucid Planet", publishDate: "Mar 4, 2022" },
  { videoId: "8ezYt7lnYQI", title: "[Special Interview] Steve McGarry, Co-founder of Grow Your Base", publishDate: "Mar 28, 2025" },
  { videoId: "9B-8JpTYHpc", title: "[Special Interview] Roneil, Audius CEO & Co-founder", publishDate: "Mar 28, 2025" },
  { videoId: "9l7DsSO7mUw", title: "[Spotlight] At the Electric Bazaar with Artist Stefan Große Halbuer", publishDate: "Mar 28, 2025" },
  { videoId: "CHagVifGhW4", title: "The WIP Meetup 08/02/2024 Raw Footage ft THREADH3ADS & FrankyNeedles", publishDate: "Aug 2, 2024" },
  { videoId: "DIEmM4HG0yo", title: "[Classic Episode] CryptoArt in VR, CryptoVoxels & the Future of Digital Art", publishDate: "Mar 28, 2025" },
  { videoId: "GxdemQg6BbU", title: "CryptoArt in VR, CryptoVoxels & the Future of Digital Art", publishDate: "Mar 28, 2025" },
  { videoId: "HPIFdHVvoGU", title: "The WIP Meetup 06/24/2021 ft Jax HideAway, Waves, CryptoArt Gallery Tour w/ Micol Mashup by Paradoxx", publishDate: "Feb 4, 2025" },
  { videoId: "IWoiDjjLs7M", title: "[Special Interview] Snowfro, Creator of artblocks.io", publishDate: "Mar 28, 2025" },
  { videoId: "IlqyXSEvmfo", title: "[Special Interview] Dannie Chu From MakersPlace", publishDate: "Mar 28, 2025" },
  { videoId: "MxD9ziAGiCs", title: "The WIP Meetup 01/09/2025 ft 2025 kickoff w/ Colborn, Reneil, Jin aka Dankvr, Trislit & Rizzle🤘", publishDate: "Jan 16, 2025" },
  { videoId: "P8LAGuVnsHY", title: "The WIP Meetup 10/24/2024 ft. Bihoz & Niftyisland Game Time Mashup by Paradoxx", publishDate: "Oct 30, 2024" },
  { videoId: "TeLVCfPxxU8", title: "Cent CryptoVoxels Art Tour & Social Money Giveaway", publishDate: "Mar 28, 2025" },
  { videoId: "ThWntpKZDOI", title: "The WIP Meetup 08/08/2024 ft HiddenForces, Rebase Finance, & Metageist Mashup by Paradoxx", publishDate: "Aug 14, 2024" },
  { videoId: "Xfg5H1543OY", title: "The WIP Meetup 05/16/2024 Pods.Media & Workstation95 Mashup by Paradoxx", publishDate: "May 24, 2024" },
  { videoId: "_AMqfa0VYlg", title: "The WIP Meetup 08/31/2023 Raw Footage Richard Oglivy Takeover Tour of the Grift District", publishDate: "Sep 1, 2023" },
  { videoId: "a9dxB06qlfY", title: "The WIP Meetup 10/24/2024 Raw Footage ft Bihoz & Niftyisland Game Time", publishDate: "Oct 24, 2024" },
  { videoId: "gxTxocxRegw", title: "The WIP Meetup 05/16/2024 Raw Footage ft CollectPods, PfeffUnit & Paradoxx Race (2/2)", publishDate: "May 17, 2024" },
  { videoId: "hdRL4QM02DE", title: "[Spotlight] Surfing the artistic waves of web3 with Alimo", publishDate: "Mar 28, 2025" },
  { videoId: "lXPdR_OLprY", title: "Sharing spicy takes and Secret Projects in the metaverse with Nate Alex", publishDate: "Mar 28, 2025" },
  { videoId: "mLuRfzL269Q", title: "The WIP Meetup 05/11/2023 Raw Footage ft. Causality w/ StrawberrySith & Flyfrogs", publishDate: "May 12, 2023" },
  { videoId: "oa-ZHgUfsC0", title: "The WIP Meetup 11/13/2025 Raw Footage ft LapinMignon & Diving into the Gotchiverse w/ @Aavegotchi", publishDate: "Nov 14, 2025" },
  { videoId: "sZ53ckyx5dY", title: "The WIP Meetup 01/23/2025 Raw Footage ft Teto w/ Post Mortem & FelixFelixFelix w/ Cypherdudes", publishDate: "Jan 24, 2025" },
  { videoId: "t2U7P3Z1X5M", title: "The WIP Meetup 07/16/2020 Field Trip to Sinkas' T Shirt Shop in Cryptovoxels", publishDate: "Apr 1, 2024" },
  { videoId: "uZA3Lly__Ak", title: "The WIP Meetup 11/14/2024 Raw Footage ft. Supahmarbler & Meme.com NFA + Leo Da Gotchi Rizzle Riddle", publishDate: "Nov 15, 2024" },
  { videoId: "ufPl2-WCiV0", title: "A Non Fungible Talk with Patricio W., Founder of POAP", publishDate: "Mar 28, 2025" },
  { videoId: "vn5DMZ6gFlY", title: "The WIP Meetup 04/11/2024 Fabiano Speziari Sandbox Game & Prizes Paradoxx Mashup", publishDate: "Apr 18, 2024" },
  { videoId: "-D61hUaCFf4", title: "The WIP Meetup 11/16/2023 Raw Footage Ft. Decentraland Music Festival & Broadside Birthday Party", publishDate: "Nov 17, 2023" },
  { videoId: "0et_PKghSUQ", title: "The WIP Meetup 05/08/2025 Raw Footage ft Volks_NFT & + Untitledxyz w/ Museum of Cryptoart Giveaway", publishDate: "May 9, 2025" },
  { videoId: "0fdVL4pm7-M", title: "The WIP Meetup 12/07/2023 Raw Footage Ft. Kane Mayfield, Rutger Vandertas & post WIPsgiving mayhem", publishDate: "Dec 8, 2023" },
  { videoId: "1y0J6NCRqfM", title: "[Special Interview] Alex Salnikov, Rarible Co-founder", publishDate: "Mar 28, 2025" },
  { videoId: "28NCPOC9fHM", title: "The WIP Meetup 05/16/2024 Raw Footage ft CollectPods, PfeffUnit & Paradoxx Race (1/2)", publishDate: "May 17, 2024" },
  { videoId: "5FhAWTKtLrc", title: "The WIP Meetup 05/13/2021 ft MARS26, Proof of Beauty, I Want My NFT Mashup by Paradoxx", publishDate: "Jan 24, 2025" },
  { videoId: "6k5bddZlY90", title: "The WIP Meetup 07/29/2021 ft AFutureModern, UTBBFT.com, CryptoMotors Mashup by Paradoxx", publishDate: "Feb 13, 2025" },
  { videoId: "9Zcl9PEGa78", title: "The WIP Meetup 2/12/2026 Raw Footage ft DaniellaDoodles Forest of Tarot Card Art", publishDate: "Feb 12, 2026" },
  { videoId: "A_CrnPJrI7M", title: "The WIP Meetup 2/5/2026 Raw Footage ft Stina Jones & Carlos Marcial", publishDate: "Feb 6, 2026" },
  { videoId: "FrACLNjrStc", title: "The WIP Meetup 06/20/2024 George Boya & Barbi S.A. + Foxyoga Birthday Mashup by Paradoxx", publishDate: "Jun 27, 2024" },
  { videoId: "HFhqKFfejcs", title: "The WIP Meetup 08/22/2025 Raw Footage ft Metageist Takeover & Merch Drop", publishDate: "Aug 22, 2025" },
  { videoId: "HcsrAbj91Os", title: "The WIP Meetup 09/28/2023 Raw Footage Ft. Metageist Migration Field Trip & Upstreet", publishDate: "Sep 29, 2023" },
  { videoId: "HuSUR6h3k7Q", title: "The WIP meetup 01/26/2023 Raw Footage ft Origin Art Museum & Pokgai", publishDate: "Jan 27, 2023" },
  { videoId: "NHu2NX0hniE", title: "The WIP Meetup 11/14/2024 Supahmarbler Meme.com NFA + Leo Da Gotchi Rizzle Riddle Mashup by Paradoxx", publishDate: "Nov 18, 2024" },
  { videoId: "Otdd1IbH6bU", title: "The WIP Meetup 09/05/2024 ft Paradoxx Art, Meme.com NFA, Rizzlefest Alpha Mashup by Paradoxx", publishDate: "Sep 12, 2024" },
  { videoId: "RToHXm9WGCk", title: "Inventing Next Level NFT Photography with Jeremy Cowart", publishDate: "Mar 28, 2025" },
  { videoId: "Rh7gJKomXFE", title: "Demystifying $WIP Coin in Footy Pajamas", publishDate: "Sep 11, 2025" },
  { videoId: "VbMnHGblqqY", title: "The WIP Meetup 11/02/2023 Raw Footage ft The Man Who Sold The World Metaverse TMWSTWM NFTCelesticals", publishDate: "Nov 3, 2023" },
  { videoId: "_3VshUJFuOQ", title: "Meta's Insta NFT Exit & Starbucks' Web3 Entrance", publishDate: "Mar 28, 2025" },
  { videoId: "cZhVDS563-Y", title: "In the right place with Johan & Mattias from MEME.com", publishDate: "Mar 28, 2025" },
  { videoId: "e1j5xYLargQ", title: "[Special Interview] Robi C., Founder & CEO of ARK Gallery", publishDate: "Mar 28, 2025" },
  { videoId: "hHh1t_n0KD0", title: "The WIP Meetup 05/23/2024 Raw Footage ft Dversio live building and gaming in custom WIP parcels", publishDate: "May 23, 2024" },
  { videoId: "hiIqIzzgNGM", title: "Talking about creating & collecting art that you love with YRDGZ", publishDate: "Mar 28, 2025" },
  { videoId: "hjNqub1P6mE", title: "The WIP Meetup 12/12/2024 Raw Footage ft. Le Bleu Elephante & Kane Mayfield", publishDate: "Dec 13, 2024" },
  { videoId: "hmssji9wYlU", title: "The WIP Meetup 01/23/2025 ft Teto & Post Mortem + FelixFelixFelix 7 Cypherdudes", publishDate: "Jan 27, 2025" },
  { videoId: "i1VdV6GrjAo", title: "Building a better future for creators with Al Morris of Koii Network", publishDate: "Mar 28, 2025" },
  { videoId: "jxsEoJaqhYE", title: "The WIP Meetup 10/05/2023 Raw Footage Ft. SlingshotDAO & Metavoxels Field Trip for SkazOne Premier", publishDate: "Oct 6, 2023" },
  { videoId: "l6cRYQfiHCQ", title: "[Special Interview] Matty from DCLBlogger", publishDate: "Mar 28, 2025" },
  { videoId: "na-u-RVF7WM", title: "[Special Interview] Viktor Radchenko, Founder of Trust Wallet", publishDate: "Mar 28, 2025" },
  { videoId: "oYSVSdW2QWw", title: "AI Agents are taking over OMG WTF LOL", publishDate: "Mar 28, 2025" },
  { videoId: "pZM6FzBdKEc", title: "The WIP Meetup 01/30/2025 ft [Redacted] beta tour🥷+ Don't Get Sidelined Mashup by Paradoxx", publishDate: "Feb 6, 2025" },
  { videoId: "qeD1Yvc16mw", title: "The WIP meetup 10/27/2022 Raw Footage ft. Cross-Metaverse Trick or Treating 🎃", publishDate: "Oct 28, 2022" },
  { videoId: "rR84beVlHvs", title: "The WIP Meetup 04/17/2025 Raw Footage ft Hyperfy Fallen Demo, Paradoxx/NineOverZero Challenge, Joel", publishDate: "Apr 18, 2025" },
  { videoId: "raJZj-cn6Hc", title: "The WIP Meetup 04/22/2021 ft Carved, Lilia, & Steve K from Zoo Tokens Mashup by Paradoxx", publishDate: "Sep 21, 2024" },
  { videoId: "vAZNMz778xc", title: "The WIP Meetup 11/09/2023 Raw Footage Ft. Patrick Amadon & Swopes", publishDate: "Nov 10, 2023" },
  { videoId: "xUAGUeNgoTc", title: "From Touching Grass To Smoking It", publishDate: "Apr 10, 2025" },
  { videoId: "zJAaWoVUVCc", title: "The WIP Meetup 08/03/2023 Raw Footage ft. Coldie's Very Dangerous Adventure Tour", publishDate: "Aug 4, 2023" },
  { videoId: "-94aqm26KME", title: "[Spotlight] Mixing music & crypto together with Indonesian music collective Sekud Beats", publishDate: "Mar 28, 2025" },
  { videoId: "-JzGzliM5Gs", title: "[Spotlight] Telling Interactive Stories with Creative Technologist Hool", publishDate: "Mar 28, 2025" },
  { videoId: "01lf9fUSFS0", title: "Talking about community, Bored Apes, and Arabian Camels with Antara", publishDate: "Mar 28, 2025" },
  { videoId: "6S4xj6gWKFo", title: "The WIP Meetup 04/10/2025 Raw Footage ft Mr. Richi Cashgrabbers, @decentraland_foundation Fashion", publishDate: "Apr 11, 2025" },
  { videoId: "6vbfUlHp5qk", title: "Things are heating up again", publishDate: "Mar 28, 2025" },
  { videoId: "7CTfRG0fzWk", title: "The WIP Meetup 03/31/2022 Raw Footage ft Numomo Art, Cryptovoxels w/ Bitpixi & Charged Particles", publishDate: "Apr 1, 2022" },
  { videoId: "8bAjqzMzzF8", title: "The WIP Meetup 09/21/2023 Raw Footage Ft. Argent DJ Set, CodeTrip Update, Field Trip to Stellacat", publishDate: "Sep 22, 2023" },
  { videoId: "E03MpEELYJA", title: "[Cent Spotlight] Deep Dive into the Creation of Saint Nakamoto with @AlottaMoney & Jivinci", publishDate: "Mar 28, 2025" },
  { videoId: "F0rOo8e3DwU", title: "[Cent Spotlight] Zooming in on Lens-based Artist @UrBen", publishDate: "Mar 28, 2025" },
  { videoId: "F8283BW-Tkw", title: "Cent Spotlight - A Reverse Spotlight on @matthew", publishDate: "Mar 28, 2025" },
  { videoId: "GxY2deF2k5Y", title: "The WIP Meetup 04/25/2024 Raw Footage ft. Cyberbrokers Takeover", publishDate: "Apr 25, 2024" },
  { videoId: "HYlk9qcxjLg", title: "The WIP Meetup 01/18/2024 Raw Footage ft. MarbleCards 5th Anniversary + Meme.com Memon Live Launch", publishDate: "Jan 19, 2024" },
  { videoId: "Jm9F_ribTnY", title: "[WIP Crew Series] Saying death to audio problems with Dragonate", publishDate: "Mar 28, 2025" },
  { videoId: "KhN6AzXfUJ0", title: "Knocking on all the doors in NFT Land with artist Cryptoyuna", publishDate: "Mar 28, 2025" },
  { videoId: "KrlWa-dSzzw", title: "The WIP Meetup 10/13/2022 Raw Footage ft Decentraland w/ Frankyneedles & Flyfrogs x ArtorDai Battle", publishDate: "Oct 14, 2022" },
  { videoId: "PSMVxROZP6U", title: "Updates! We got your metaverse updates with Leandro of CryptoMotors", publishDate: "Mar 28, 2025" },
  { videoId: "PcGE5iQYHQk", title: "The WIP Meetup 04/06/2023 Raw Footage ft Forum3 & Starbucks NFTs, Leonie Engel, & RARA", publishDate: "Apr 6, 2023" },
  { videoId: "PuQYoVxIlKM", title: "[Cent Spotlight] Sharing Human Stories with Digital Artist Osinachi", publishDate: "Mar 28, 2025" },
  { videoId: "Qt4GQI21csA", title: "[Special Interview] Simona Pop, Head of Community at Status.im", publishDate: "Mar 28, 2025" },
  { videoId: "TGnlGkPLcrI", title: "[Special Interview] Sid Kalla from TryRoll", publishDate: "Mar 28, 2025" },
  { videoId: "TSk-1f_2X6A", title: "[Special Interview] Nate Geier & Carolin Wend from Mintbase.io", publishDate: "Mar 28, 2025" },
  { videoId: "UkjgracmlyE", title: "Building in the metaverse with meta architect Pointshark", publishDate: "Mar 28, 2025" },
  { videoId: "Z3opOB67NHg", title: "M○C△ (Museum of Crypto Art) on MARS", publishDate: "Mar 28, 2025" },
  { videoId: "ZyeRO_I4sCU", title: "[Spotlight] Buy any Tweet with Valuables by Cent", publishDate: "Mar 28, 2025" },
  { videoId: "_sCuN0HQl8s", title: "The WIP Meetup 11/20/2025 Raw Footage ft Wipsgiving 2025 Pt 2", publishDate: "Nov 21, 2025" },
  { videoId: "aY4WtbBx5sI", title: "[Spotlight] Playing simple creative games with artist Richard F. Yates", publishDate: "Mar 28, 2025" },
  { videoId: "beoGBvDgvTI", title: "[Spotlight] Mining Metaverse Alpha with WhaleShark", publishDate: "Mar 28, 2025" },
  { videoId: "c9P_PAHk6dc", title: "Rizzle for CEO of Cryptovoxels & A look into Stealcam", publishDate: "Mar 28, 2025" },
  { videoId: "ffBvPuvreSo", title: "The WIP Meetup 09/14/2023 Raw Footage Ft. Dat Ogar and MisfitPixels", publishDate: "Sep 15, 2023" },
  { videoId: "gpYpxwBoiI4", title: "The WIP Meetup 03/06/2025 ft HPrivakos, ElatedPixel Tour + AlottaMoney Tribute Mashup by Paradoxx", publishDate: "Mar 12, 2025" },
  { videoId: "gtYFJzvG4Zc", title: "The WIP Meetup 03/21/2024 Raw Footage Ft. Charl3s from Nifty Island 2/2", publishDate: "Mar 22, 2024" },
  { videoId: "h6v26o4rGH0", title: "[Special Interview] Alex, PM at Rarible", publishDate: "Mar 28, 2025" },
  { videoId: "iKSWVC-7rik", title: "The WIP meetup 01/05/2023 Raw Footage ft FlyfrogNFT Tadpole Breeding & Break Things w/ Fractilians", publishDate: "Jan 6, 2023" },
  { videoId: "irP60587Rdo", title: "[Cent Spotlight] Scribing on the Blockchain with @conlan", publishDate: "Mar 28, 2025" },
  { videoId: "iyBmasDMUMA", title: "The WIP Meetup 08/17/2023 Raw Footage ft FlyFrogs Racing & Inside the Art of Spherical Art", publishDate: "Aug 18, 2023" },
  { videoId: "k9h30SxYPJo", title: "The WIP Meetup 03/09/2023 Raw Footage ft Metavoxelz Deep Dive into Cryptovoxels", publishDate: "Mar 10, 2023" },
  { videoId: "lYame5c0EdM", title: "Clanging on about #OnChainChain with #OnChainGang OG Rizzle", publishDate: "Mar 28, 2025" },
  { videoId: "n2MKbPKfwik", title: "Proof of Work Amidst the NFT Land Holidaze", publishDate: "Mar 28, 2025" },
  { videoId: "pQdnYePQviM", title: "The WIP Meetup 02/10/2022 Raw Footage ft Metageist Build, Musashi, Bitlectro & Derpy Birds", publishDate: "Feb 11, 2022" },
  { videoId: "sXfIhUsYsjA", title: "The WIP Meetup 06/08/2023 Raw Footage ft. GasHawk.io, OlgaForce 3D, SkyBravo talking Rizzlefest", publishDate: "Jun 9, 2023" },
  { videoId: "tQzapa_xyBs", title: "The WIP Meetup 05/12/2022 Raw Footage ft Fabiano Speziari, Rogan X & The Guild w/ Rutger Van Der Tas", publishDate: "May 13, 2022" },
  { videoId: "tZuomhC2O7s", title: "[MARS Classic] A Non Fungible Talk with POAP founder Patricio W.", publishDate: "Mar 28, 2025" },
  { videoId: "x2j55Ux0iOg", title: "The WIP Meetup 09/07/2023 Raw Footage Ft. Firstmate.xyz & Voxvienne", publishDate: "Sep 8, 2023" },
  { videoId: "yTCIhAsl9kQ", title: "[Special Interview] Jess Sloss, Founder of Seed Club", publishDate: "Mar 28, 2025" },
  { videoId: "zmSDyAc_fJE", title: "[Special Interview] Eclectic Method, Video Remix & Musical Animations Artist", publishDate: "Mar 28, 2025" },
  { videoId: "-0RrCcXKyw8", title: "The WIP Meetup 06/09/2022 Raw Footage ft HyperCastle Explorers, Metaverse Alliances, Flyfrogs Battle", publishDate: "Jun 10, 2022" },
  { videoId: "-ssuCyNtveU", title: "Unearthing $B20, Balancing Technical Complexity & Community", publishDate: "Mar 28, 2025" },
  { videoId: "07Pzun67qBg", title: "[Special Interview] Leandro & Alegria, CryptoMotors, PixelChain, Voxel Architects & $WHALE", publishDate: "Mar 28, 2025" },
  { videoId: "0YQ5nZJyrkQ", title: "Historic Onchain Projects Meet New Era Onchain Social", publishDate: "Mar 28, 2025" },
  { videoId: "10EeXXZLQMI", title: "[Special Interview] Josie Bellini, Crypto Artist", publishDate: "Mar 28, 2025" },
  { videoId: "1TdbOJGjdVg", title: "Making Metaverse Music NFTs with Jonathan Mann", publishDate: "Mar 28, 2025" },
  { videoId: "1tCF_qc6xDc", title: "[Special Interview] Twobadour, Co-steward of Metapurse", publishDate: "Mar 28, 2025" },
  { videoId: "1uZ4xlR6TDU", title: "Everything that happened at NFT NYC (besides the conference)", publishDate: "Mar 28, 2025" },
  { videoId: "1yayIHlpcmQ", title: "[Spotlight] Cutting it up with collagist Lucidhouse", publishDate: "Mar 28, 2025" },
  { videoId: "40ZKX8K48d8", title: "We're so close (and no one is here to see it)", publishDate: "Mar 28, 2025" },
  { videoId: "4Q9FaZxGeK0", title: "[Special Interview] Marbling the Internet with Marble.Cards Co-Founder Johan Unger", publishDate: "Mar 28, 2025" },
  { videoId: "4SmR4a2xRHs", title: "Onchain is the new online? Always has been.", publishDate: "Mar 28, 2025" },
  { videoId: "4eVGh0W0Qi8", title: "Meditating in the Metaverse with Foxyoga", publishDate: "Mar 28, 2025" },
  { videoId: "6Ub7ReUdQRA", title: "Azeem from Pollinate.io on MARS", publishDate: "Mar 28, 2025" },
  { videoId: "6eFPP9hajpE", title: "Memecoin Experiment No. 69 - Up.Army", publishDate: "Mar 28, 2025" },
  { videoId: "7Pa0BDehzx0", title: "Another icon gone, but not forgotten", publishDate: "Mar 28, 2025" },
  { videoId: "B9tYZUJ1Gqs", title: "Riffing on NFTs & Jazz with Melody Poet Mike Casey", publishDate: "Mar 28, 2025" },
  { videoId: "CJ0a0KjmDrQ", title: "Lewis Mumford, Invisible Cities, Cent & The Future of Podcasting", publishDate: "Mar 28, 2025" },
  { videoId: "CQiVx-SZ-xw", title: "The WIP Meetup 05/09/2024 Raw Footage ft. Meme.com sneak peek & WizardX", publishDate: "May 10, 2024" },
  { videoId: "CasAEWdYMA0", title: "Metaverse Differentiation & Lisbon Hype", publishDate: "Mar 28, 2025" },
  { videoId: "E4cl0y7NfVg", title: "A presidential recalibration full of agentic frogs hits crypto", publishDate: "Mar 28, 2025" },
  { videoId: "EFOLHdaiS5w", title: "3 Year Anniversary Episode with Matthew & Rizzle", publishDate: "Mar 28, 2025" },
  { videoId: "EXqF4lrD6xo", title: "[Spotlight] Talking scarecrows, bodies & cryptoart with Kitty Bast", publishDate: "Mar 28, 2025" },
  { videoId: "FXz8xhaUZ-M", title: "The WIP Meetup 08/10/2023 Raw Footage ft Interface & Untitled.xyz tour of Museum of Crypto Art ROOMS", publishDate: "Aug 11, 2023" },
  { videoId: "Fsl0iq0DEag", title: "CryptoArt, The Devil's Advocate Episode", publishDate: "Mar 28, 2025" },
  { videoId: "G3acrDmxp10", title: "The WIP Meetup 08/05/2021 ft Skeenee, NFT42 & SandyMe0ws + Hackatao & Blondie Mashup by Paradoxx", publishDate: "Feb 13, 2025" },
  { videoId: "IqMo4lv8PdM", title: "The WIP Meetup 04/13/2023 Raw Footage ft. Polygonal Mind, CryptoAvatars & Scuube", publishDate: "Apr 14, 2023" },
  { videoId: "JDJM0ReMrUA", title: "The WIP Meetup 08/11/2022 Raw Footage ft HEXGO, 1KX Network & Lighthouse", publishDate: "Aug 12, 2022" },
  { videoId: "JiAGx8tgesk", title: "The WIP Meetup 09/18/2025 Raw Footage ft Meme.com alpha + Ezincrypto & Jose Cabrera", publishDate: "Sep 19, 2025" },
  { videoId: "M1Dle6oB38o", title: "[Spotlight] Making moves with Gif Master Edmotions", publishDate: "Mar 28, 2025" },
  { videoId: "NYdconr9nvc", title: "[Spotlight] Big Talk with OG Centian Green Giant", publishDate: "Mar 28, 2025" },
  { videoId: "PCMzW_Jnokw", title: "[Special Interview] Nate & Carolin, Mintbase.io", publishDate: "Mar 28, 2025" },
  { videoId: "PyehQOdaSE4", title: "Making memes great again with Johan Unger of Meme.com", publishDate: "Mar 28, 2025" },
  { videoId: "QoPE2-MFNxc", title: "Rizzle chats with with Amir from Bomani Digital", publishDate: "Mar 28, 2025" },
  { videoId: "RlcT9hf2aks", title: "The WIP Meetup 06/15/2023 Raw Footage ft Vipe Roadmap Alphaleak", publishDate: "Jun 16, 2023" },
  { videoId: "Rm-4ezsWyqQ", title: "Blurred Lines at the $hitcoin & $memecoin Casino", publishDate: "Mar 28, 2025" },
  { videoId: "S-R32zR2mCM", title: "Rizzle Day oh and Art Basel", publishDate: "Mar 28, 2025" },
  { videoId: "S8fqSCmHhoM", title: "The WIP Meetup 03/30/2023 Raw Footage ft Aavegotchi Deep Dive + Fabiano & Patrizia Jump Course", publishDate: "Mar 31, 2023" },
  { videoId: "UF-7NYeVDrk", title: "[Special Interview] Jesse Johnson, Creator of Bullionix.io", publishDate: "Mar 28, 2025" },
  { videoId: "VEMCfwuNSZM", title: "Real talk about art, sex work & web3 with Cryptonatrix", publishDate: "Mar 28, 2025" },
  { videoId: "VsTraBwA_PY", title: "Metaverse Musing with the two Matts from Intro To Music Theory", publishDate: "Mar 28, 2025" },
  { videoId: "WFZ7MPjB5Ec", title: "A Crazy Tuesday in Cryptoland", publishDate: "Mar 28, 2025" },
  { videoId: "WpcmaaHMrDg", title: "Some on-chain⛓ freudenfreude with a dash of off-chain schadenfreude", publishDate: "Mar 28, 2025" },
  { videoId: "XwQ5COTiHt0", title: "A New Metaverse Era Dawns", publishDate: "Mar 28, 2025" },
  { videoId: "YF-jMFgKSkU", title: "Ribbit. An interview from the pond with FlyFrogs creators Josh & Molly", publishDate: "Mar 28, 2025" },
  { videoId: "YUWcLZ-x0pQ", title: "Marrying NFTs & Music with Lin Dai, CEO of OneOf", publishDate: "Mar 28, 2025" },
  { videoId: "ZCgblRdlIUs", title: "The WIP Meetup 05/18/2023 Raw Footage ft MESHfair Prev in Decentraland w/ Bay Backner & Fractilians", publishDate: "May 19, 2023" },
  { videoId: "ZHYKOzJStw8", title: "Marrying Movies with NFTs in the Metaverse with Jan & David from MovieShots", publishDate: "Mar 28, 2025" },
  { videoId: "_Qoc3BWUhe4", title: "Streaking💫 on Nifty Island While Farcasting About Polymarket Prediction Markets", publishDate: "Mar 28, 2025" },
  { videoId: "af5EXSaxb4U", title: "The WIP Meetup 10/20/2022 Raw Footage ft Ogar, Pointshark, Bitpixi", publishDate: "Oct 21, 2022" },
  { videoId: "b3tJeG6Ftug", title: "[Special Interview] Seb & Nathan, The Sandbox", publishDate: "Mar 28, 2025" },
  { videoId: "cvEy84QLHWk", title: "The Johan Love Fest & MarbleCards Turns Five!", publishDate: "Mar 28, 2025" },
  { videoId: "d12iZ6W0BjU", title: "Learning and earning in the metaverse with Esther, founder of Hundo.xyz", publishDate: "Mar 28, 2025" },
  { videoId: "dQqExdK4O-8", title: "Matt gives Rizzle NFC Summit FOMO", publishDate: "Mar 28, 2025" },
  { videoId: "eRTaf-syjjM", title: "We Are The Lore", publishDate: "Mar 28, 2025" },
  { videoId: "eRlUfTQSmWg", title: "[Spotlight] Peeking Into the Creative Process of Bryan Brinkman", publishDate: "Mar 28, 2025" },
  { videoId: "fKT5WBYs9zA", title: "[Special Interview] Hugo McDonaugh, Cofounder of Cryptograph", publishDate: "Mar 28, 2025" },
  { videoId: "fSkEG5mYjfw", title: "Leading majestic zora horses to the purple water cooler", publishDate: "Mar 28, 2025" },
  { videoId: "fxfHTDNxHbY", title: "The WIP Meetup 05/26/2022 Raw Footage ft AsyncArt, Hom3work & @songadaymann", publishDate: "May 27, 2022" },
  { videoId: "gVKWo-WCQDQ", title: "The WIP Meetup 11/30/2023 Raw Footage ft Wipsgiving Day Parade w/ Metaverse Makers, Jin, Boomboxhead", publishDate: "Dec 1, 2023" },
  { videoId: "gd4-AfaMWVE", title: "Where do we go from here?", publishDate: "Mar 28, 2025" },
  { videoId: "ggkFqSr7vhg", title: "The WIP meetup 11/10/2022 Raw Footage ft. MomentumXYZ", publishDate: "Nov 11, 2022" },
  { videoId: "hR0kQRSIqCs", title: "The WIP Meetup 03/24/2022 Raw Footage ft KikiCity, Dragonate & Emanate w/ DJ Lethal Skillz", publishDate: "Mar 25, 2022" },
  { videoId: "j-nqf2b0CBY", title: "[Cent Spotlight] Talking Tokenized Writing with Thomas Dylan Daniel", publishDate: "Mar 28, 2025" },
  { videoId: "mDYfRnMPy5M", title: "[Cent Spotlight] Programing the Future of Art with Matt Kane", publishDate: "Mar 28, 2025" },
  { videoId: "mhy5sSypyKs", title: "NFTs in the Minds of Normies", publishDate: "Mar 28, 2025" },
  { videoId: "mis2gfz1B-E", title: "From NFT.NYC to RIZZLEFEST", publishDate: "Mar 28, 2025" },
  { videoId: "mxHFPXWNry4", title: "MARS goes Onchain & Crypto Social Projects in their Off-season", publishDate: "Mar 28, 2025" },
  { videoId: "ozIJSXowfMQ", title: "[Special Interview] Jiho, Co-founder & Head of Growth at Axie Infinity", publishDate: "Mar 28, 2025" },
  { videoId: "qP6KnOm2w4g", title: "[Spotlight] Waxing Poetic with the Poet Positioned", publishDate: "Mar 28, 2025" },
  { videoId: "qUwdFDjI3Ik", title: "The WIP Meetup 03/23/2023 Raw Footage Ft Metageist World in Oncyber & Basketball w/ Scuube", publishDate: "Mar 24, 2023" },
  { videoId: "qXNS9QuDEbo", title: "[Spotlight] Staying Stabby with artist WoodenCyclops", publishDate: "Mar 28, 2025" },
  { videoId: "quZrDqvycdI", title: "The WIP meetup 11/17/2022 Raw Footage ft. WIPSGIVING high staked sumo fight to the death", publishDate: "Nov 17, 2022" },
  { videoId: "r8XB4RGbgDI", title: "Shouting out NFT Music with Zora's Latashá", publishDate: "Mar 28, 2025" },
  { videoId: "rQvZoZJ-viw", title: "The WIP Meetup 10/26/2023 Raw Footage ft AnonSnail Halloween Mega NFT Giveaway Competition & Contest", publishDate: "Oct 27, 2023" },
  { videoId: "rUXjHg0vQng", title: "[Special Interview] The Terra Virtua Squad", publishDate: "Mar 28, 2025" },
  { videoId: "s0ezClSeQoY", title: "The WIP Meetup 05/25/2023 Raw Footage ft ChangeDao & Live update from Paradoxx & Metageist", publishDate: "May 26, 2023" },
  { videoId: "s1ThPpPMniE", title: "Forever Alone in Crypto & Secret Centa", publishDate: "Mar 28, 2025" },
  { videoId: "sRPd0GBhnfQ", title: "[Special Interview] A Mind Blowing Talk with Conlan, Founder of Async.Art", publishDate: "Mar 28, 2025" },
  { videoId: "tdZsF8YL3zY", title: "The WIP Meetup 07/08/2021 ft Kaigani, ArtSoFly, SphericalArt, Paradoxx, Cawa George Mash by Paradoxx", publishDate: "Feb 10, 2025" },
  { videoId: "txdo8WCCgOY", title: "[Special Interview] Drew Harding, Co-founder of The MetaFactory", publishDate: "Mar 28, 2025" },
  { videoId: "u67_Z_5Y0GA", title: "[Special Interview] Vii, CTO of Lendroid", publishDate: "Mar 28, 2025" },
  { videoId: "ue9ejR_4LvM", title: "The WIP Meetup 05/05/2022 Raw Footage ft The Open Metaverse w/ Dankvr aka Jin, Evin & Stellabelle", publishDate: "May 6, 2022" },
  { videoId: "vDRcXnFR7qA", title: "[MARS Classic] A Reverse Spotlight on Matthew [30 Aug 2019]", publishDate: "Mar 28, 2025" },
  { videoId: "wGsL18QgbdM", title: "Blockchain Vibe Check", publishDate: "Mar 28, 2025" },
  { videoId: "wQiaE3rskTw", title: "Devcon V, Gamification & Female Crypto", publishDate: "Mar 28, 2025" },
  { videoId: "wak6ghId4gs", title: "Hyping up the Builders", publishDate: "Mar 28, 2025" },
  { videoId: "xurGznpxelM", title: "IRL + VR CryptoArt Shows & CryptoVoxel Wearables (WEAR)", publishDate: "Mar 28, 2025" },
  { videoId: "y7-5ISg13FI", title: "The WIP meetup 03/02/2023 Raw Footage ft ArdonLukas and jaygotgame", publishDate: "Mar 3, 2023" },
  { videoId: "yny_xjTYvqA", title: "[Spotlight] The Recursively Awesome VHS Artist TheSarahShow", publishDate: "Mar 28, 2025" },
  { videoId: "yxoyNOOGaNM", title: "Setting the Cent Table", publishDate: "Mar 28, 2025" },
  { videoId: "zSkfyOMCXUw", title: "The WIP Meetup 07/18/2024 FlyFrogs Decentralized Toy Creation and Design Mashup by Paradox", publishDate: "Jul 25, 2024" },
  { videoId: "zo9pnsqK-NQ", title: "[MARS Classic] Jiho, Co-founder & Head of Growth at Axie Infinity (2020 April 4)", publishDate: "Mar 28, 2025" },
  { videoId: "1ccUr4RPwQY", title: "The WIP meetup 12/15/2022 Raw Footage ft. Aavegotchi & CryptoAvatars", publishDate: "Dec 16, 2022" },
  { videoId: "48_WsAiyBCg", title: "The WIP Meetup 08/25/2022 Raw Footage ft Brookhawk, Transient Labs, ZapperFi & Dan Sickles", publishDate: "Aug 26, 2022" },
  { videoId: "5COwkflypdg", title: "Hot takes on ETH Denver", publishDate: "Mar 28, 2025" },
  { videoId: "6YfzrDrsX9w", title: "The WIP Meetup 08/18/2022 Raw Footage ft Artist Royalties w/ AsyncArt, Spheroid Universe & Cent", publishDate: "Aug 19, 2022" },
  { videoId: "6o15XnMVTe4", title: "The WIP meetup 12/22/2022 Raw Footage ft. A Very Rare Apepe Christmas Party", publishDate: "Dec 23, 2022" },
  { videoId: "A_neuYCfbAk", title: "If you're not having fun you're doing crypto wrong", publishDate: "Mar 28, 2025" },
  { videoId: "CdKixZy3VXc", title: "The WIP Meetup 03/17/2022 Raw Footage ft Brinkman, Movement Generation, Kane Mayfield, Sov, UndeadLu", publishDate: "Mar 18, 2022" },
  { videoId: "DicLBa2DmbM", title: "The WIP Meetup 06/22/2023 Raw Footage ft Aavegotchi Rager in Monaverse", publishDate: "Jun 23, 2023" },
  { videoId: "F5K7cDSnvk8", title: "The WIP Meetup 02/09/2023 Raw Footage ft Boomboxhead, Jin aka Dankvr, Dragonate", publishDate: "Feb 10, 2023" },
  { videoId: "GoJHCEF4zNE", title: "The WIP meetup 02/02/2023 Raw Footage ft Broadside, VectorMeldrew, StratfordRex, MattMason, Foxyoga", publishDate: "Feb 3, 2023" },
  { videoId: "IN7gcGdNQBU", title: "The WIP Meetup 07/21/2022 Raw Footage ft SoundClash, Omega Runner & NFTconomy", publishDate: "Jul 22, 2022" },
  { videoId: "R2YOmJLKhqo", title: "The WIP meetup 11/03/2022 Raw Footage ft. Fromoville Bob Ross Parody by J.J. Weinberg in Monaverse", publishDate: "Nov 4, 2022" },
  { videoId: "RV2mGGeeRW0", title: "The WIP Meetup 07/27/2023 Raw Footage ft Bring Your Kid To The WIP Day", publishDate: "Jul 28, 2023" },
  { videoId: "T1bHngCRYnY", title: "The WIP meetup 01/12/2023 Raw Footage ft Iraxlab Spatial Tour + NFT Garage", publishDate: "Jan 13, 2023" },
  { videoId: "UzPv09GaDoo", title: "The WIP meetup 12/01/2022 Raw Footage Ft. SteadyBreaks", publishDate: "Dec 2, 2022" },
  { videoId: "ZUOgN9V5dh0", title: "Rizzle Rambles on Decentralization & Interoperability", publishDate: "Mar 28, 2025" },
  { videoId: "cjEj3OQvJ2Q", title: "The WIP Meetup 10/06/2022 Raw Footage ft Simulacra & CatsWillEatYou", publishDate: "Oct 7, 2022" },
  { videoId: "dL2aiZMZtZE", title: "The WIP Meetup 09/15/2022 Raw Footage ft Bryan Brinkman Cryptovoxels Tour & NiftyGateWay Sneak Peek", publishDate: "Sep 16, 2022" },
  { videoId: "iF3R2_gPRnM", title: "The WIP Meetup 06/30/2022 Raw Footage ft Connie Digital, Marble School & NFTstudios", publishDate: "Jul 1, 2022" },
  { videoId: "nK5PosXTN6I", title: "Did you know you can send ETH to anyone with an ETH address?!?", publishDate: "Mar 28, 2025" },
  { videoId: "oXFJjo4POuE", title: "The WIP Meetup 07/14/2022 Raw Footage ft State of Cryptovoxels Metaverse Benjy Bitpixi & CVminigames", publishDate: "Jul 15, 2022" },
  { videoId: "pM9h3huamD0", title: "The WIP Meetup 02/16/2023 Raw Footage ft Rare Scrilla, Room in Eight & Fractilians", publishDate: "Feb 17, 2023" },
  { videoId: "q-gKfplUQz4", title: "The WIP Meetup 03/10/2022 Raw Footage ft AlottaMoney Tribute Parcel by Brookhawk, 0xsplits, Brinkman", publishDate: "Mar 11, 2022" },
  { videoId: "qnD6nvS_5LM", title: "Matt finds a new web3 app & Rizzle fades ENS", publishDate: "Mar 28, 2025" },
  { videoId: "sTC2PMfExJ8", title: "The WIP meetup 01/19/2023 MarbleCards 4 Year Anniversary", publishDate: "Jan 20, 2023" },
  { videoId: "sl2NPJxzLjM", title: "The WIP Meetup 06/02/2022 Raw Footage ft Chaos, CTRL Builders & CryptoArcade", publishDate: "Jun 3, 2022" },
  { videoId: "tkVpJEEdL8U", title: "The WIP Meetup 07/20/2023 Raw Footage ft CodeTrip & Decentraland MESHfair", publishDate: "Jul 21, 2023" },
  { videoId: "vr5v5-49vGk", title: "The WIP Meetup 09/29/2022 Raw Footage ft Cult CryptoArt Temple Ritual in Monaverse + Fractilians", publishDate: "Sep 30, 2022" },
  { videoId: "wSd2lPKJHhY", title: "Deep diving into Voxels and the metaverse with Bitpixi", publishDate: "Mar 28, 2025" },
  { videoId: "ykrH9Qur1yg", title: "The WIP Meetup 09/22/2022 Raw Footage ft Interactive Games w/ RareCandy 🍬", publishDate: "Sep 23, 2022" },
];
